# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/modules/vault/versions.tf" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "18:00"
      timezone: "America/Los_Angeles"

  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/modules/tls-private/versions.tf" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "18:00"
      timezone: "America/Los_Angeles"

  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/modules/google-kms/versions.tf" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "18:00"
      timezone: "America/Los_Angeles"
      
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/modules/google-gke-cluster/versions.tf" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "18:00"
      timezone: "America/Los_Angeles"
      
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/modules/google-cloud-dns/versions.tf" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "18:00"
      timezone: "America/Los_Angeles"

  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/modules/acme-cert/versions.tf" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "18:00"
      timezone: "America/Los_Angeles"
